### ISSUE TITLE
ng2-bootstrap问题

### ISSUE THREAD

**Issue by Chaiyelu** [angular-programming/angular2-questionnaire#1]
![image](https://cloud.githubusercontent.com/assets/13944889/22133722/febb4cda-defc-11e6-854b-1e576b124d18.png)
请问这个是什么问题，该如何解决。
另外代码中ng2-bootstrap文件目录，和现在用npm，install下来的目录不一样。
![image](https://cloud.githubusercontent.com/assets/13944889/22133791/763455cc-defd-11e6-86c5-6a257ae24f3c.png)
并没有ng2-bootstrap/component/这一级目录。#

**Comment by lightningtgc** [comment]
Hi，不好意思。ng2-bootstrap 变化重构速度过快，我们是基于1.1.16 版本进行开发，你可以单独安装这个版本，或者把package.json里面 ng2-bootstrap 版本前面的 ^ 符号去掉，再进行安装。谢谢反馈。

**Comment by Chaiyelu** [comment]
谢谢，问题已经解决了，确实是ng2-bootstrap版本的问题。

**Comment by KevinZhang111** [comment]
我也遇到了同样的问题，重新安装ng2-bootstrap 1.1.16 版本后解决。但是我按照书上讲解的步骤写好home.component.ts , home.module.ts 和 home.component.html 三个文件，并将示例代码文件夹中的 assets\img 文件夹拷贝到了我的工程中。但是浏览器运行并没有出现书中的首页界面。依然是空白。

控制台报错如下：
Uncaught Error: Module must be loaded as AMD or CommonJS ng2-bootstrap.umd.min.js:5680

我看到有人问同样的问题，但是不明白为何我的页面还是空白，好像代码完全没有生效。
![capture](https://cloud.githubusercontent.com/assets/27321850/25088127/882c6cea-23a6-11e7-9022-db9b18004351.JPG)
