### ISSUE TITLE
书中第379页中storage不对

### ISSUE THREAD

**Issue by GerryLon** [angular-programming/angular2-questionnaire#11]
原代码: `const storage = require('lowdb/file-async');`
我修改为: `lowdb/lib/storages/file-async`就好了.

**Comment by lizhonghui** [comment]
恩，lowdb目录结构新版本改动了，0.13.1版本好像使用 `require('lowdb/lib/file-async')`。

**Comment by GerryLon** [comment]
好的, 谢谢
