### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Arvin-zhu** [angular-programming/angular2-questionnaire#2]
**## Uncaught Error: Module must be loaded as AMD or CommonJS**
    at ng2-bootstrap.umd.min.js:5680
    at ng2-bootstrap.umd.min.js:1
    at ng2-bootstrap.umd.min.js:5674

##  **(SystemJS) exports is not defined**
	ReferenceError: exports is not defined
	    at eval (http://localhost:5555/app/shared/models/question.model.js:2:23)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/models/index.js:6:10)
	    at eval (http://localhost:5555/app/shared/models/index.js:11:4)
	Evaluating http://localhost:5555/app/shared/models/question.model.js
	Evaluating http://localhost:5555/app/shared/models/index.js
	Evaluating http://localhost:5555/app/shared/index.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
请教一下这是什么原因导致的，该怎么解决啊

**Comment by Arvin-zhu** [comment]
![Uploading 捕获.jpg…]()

**Comment by liudianliang** [comment]
启动报错，相同的问题

**Comment by lizhonghui** [comment]
谢谢反馈！
由于 TypeScript 在 npm 上的版本已经更新到2.2，有一些兼容性问题。
`exports is not defined` 这个启动错误已经修复，拉取最新代码重新运行即可 ~

**Comment by Arvin-zhu** [comment]
十分谢谢，问题解决了。
