### ISSUE TITLE
无法登录注册

### ISSUE THREAD

**Issue by liudianliang** [angular-programming/angular2-questionnaire#3]
ng2-bootstrap.umd.min.js?1488201334751:5680 Uncaught Error: Module must be loaded as AMD or CommonJS

**Comment by lizhonghui** [comment]
你好 ~
我本地试了下，也出现这个错误，但可以正常注册登录，请确保后台 server 是否已经启动，若已启动，检查了ajax请求的返回包是否正常。
> 贴出来的这个错误应该不影响正常功能，这个错误应该是某个npm包更新了导致兼容性问题，正常排查中 ~

**Comment by liudianliang** [comment]
谢谢您的及时回答，我没用过json-server，我开了两个命令行，一个开后台，后台不关没法再开前台，我又重新开了一个命令行，启动前台，是这个套路吗？

**Comment by lizhonghui** [comment]
是的，前后台需要运行着

**Comment by liudianliang** [comment]
这个的demo不错，感谢您的解答
