### ISSUE TITLE
carousel not work auto

### ISSUE THREAD

**Issue by alexwjm** [angular-programming/angular2-questionnaire#5]
轮播插件好像不能自动跳转。。。

**Comment by yorts52** [comment]
这个需要配置轮播时间，参考: https://valor-software.com/ng2-bootstrap/#/carousel#dynamic

解决这类问题要学会看文档，一般 demo 很难覆盖所有的使用情形，在本例中解决方案如下：
源码: https://github.com/angular-programming/angular2-questionnaire/blob/d08f894b719fbdf470027361cb4c3ceea80859e1/frontend/src/client/app/home/home.component.html#L4

```html
- <carousel>
+ <carousel [interval]="3000">
```

**Comment by alexwjm** [comment]
多谢，node_modules 下源码说默认interval为5秒，手动不设也可以，貌似在ngFor的情况下必须设置此变量

**Comment by yorts52** [comment]
给出的链接后面有参数说明:

> Type: number
> Delay of item cycling in milliseconds. If false, carousel won't cycle automatically.

**Comment by alexwjm** [comment]
多谢
代码原注释比较奇怪,说的是proerties
而且前几个example （非循坏）不设置都是默认可以工作的
interval	
Type: number
Default value: 5000
Default interval of auto changing of slides

**Comment by yorts52** [comment]
简单看了一下源码, 你说的注释是这个:
https://github.com/valor-software/ng2-bootstrap/blob/a33dc10724bbd7c338f0fbd4fd4935eaf73133f3/src/carousel/carousel.component.ts#L13
https://github.com/valor-software/ng2-bootstrap/blob/c6ba82d7bb51136c76ae9b395bb50e0c3ae27242/src/carousel/carousel.config.ts#L6

实际上 interval 是这里处理的
https://github.com/valor-software/ng2-bootstrap/blob/development/src/carousel/carousel.component.ts#L74-L80
https://github.com/valor-software/ng2-bootstrap/blob/a33dc10724bbd7c338f0fbd4fd4935eaf73133f3/src/carousel/carousel.component.ts#L271

**Comment by yorts52** [comment]
这里确实存在误导,  ng2 经历的版本变更太多了, ng2-bootstrap 也一样经历过很多次重构, 导致文档注释和代码有些混乱

**Comment by alexwjm** [comment]
很高兴一起讨论，贵书已拜读，有浅入深，层次有序，覆盖面广，很推荐大家来看
