### ISSUE TITLE
请教一个关于移动端的问题，

### ISSUE THREAD

**Issue by liudianliang** [angular-programming/angular2-questionnaire#8]
angular2 是否适合开发移动端页面呢？如果可以，用那个UI框架好呢？可否推荐下？

**Comment by lizhonghui** [comment]
Angular 2+ 本身就是优先为移动设计的。
与Angular贴合比较紧密的UI框架有自家的Material、ng2-bootsrap，二者都是响应式UI框架，缺点可能是体积比较大。
其实还有很多跟框架无关的独立UI框架，如weui等，也可以考虑使用。

**Comment by liudianliang** [comment]
非常感谢
